# Use the official PostgreSQL image as a parent image
FROM postgres:12

# Set the environment variables
ENV POSTGRES_DB students
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD postgres

# Expose the PostgreSQL port
EXPOSE 5432